### ISSUE TITLE
New type of track field: Link

### ISSUE THREAD

**Issue by harmslijper** [GemsTracker/gemstracker-library#343] opened 2018-08-15 09:27 UTC
Trackfield where respondent track ID from another track is stored. This way different tracks can be linked. Selction criteria for filling the field could be (as a starter):
- select track: drop down menu of available tracks
- start or end date of the selected track

**Comment by mennodekker** [comment] 2019-02-18 14:45
Duplicate of #393

**Closed by mennodekker** 2019-02-18 14:45 UTC
Labels: feature request
