### ISSUE TITLE
Unsubscribe option affects all questionnaires

### ISSUE THREAD

**Issue by Jbakx** [GemsTracker/gemstracker-library#591] opened 2020-09-07 14:17 UTC
**problem**
Patients should not be able to unsubscribe for **all** questionnaires, since some questionnaires are mandatory (In case of Pulse: patients should receive the anesthesia questionnaire, even when they unsubscribed).  

**requested result**
We want the abbility to set certain questionnaires as 'mandatory' which overwrites the 'unsubscribe'. In the end, we want people to receive all questionnaires when subscribed and to only receive mandatory questionnaires when unsubscribed

**Comment by mddejong** [comment] 2021-02-17 13:13
Duplicate of #603

**Closed** 2021-02-17 13:13 UTC
